---

- name: Cleanup pre-start of test (conditional)
  shell: rm -rf {{ hostvars[inventory_hostname]['gbench_client_mountpoint'] }}fio/*
  args:
    executable: /bin/bash
  when:
    - inventory_hostname == groups['clients'][0]
    - test_vars.cleanup_pre and fio_iter_index == 0

- name: Cleanup client cache
  include: cleanup_cache.yml
  when:
    - test_vars.cleanclientcache
    - inventory_hostname in groups['clients']

- name: Cleanup server cache
  include: cleanup_cache.yml
  when:
    - test_vars.cleanservercache
    - inventory_hostname in groups['servers']

- name: Run a FIO test
  shell: fio {{ fio_working_directory }}/test.ini --output-format=json --client={{ fio_working_directory }}/clients.list > "{{ fio_json_output }}"
  args:
    executable: /bin/bash
  when:
    - inventory_hostname == groups['clients'][0]

- name: Retrieve test results
  fetch:
    src: "{{ fio_json_output }}"
    dest: "/tmp/fio-test-{{ test_vars.testname }}-iteration-{{ fio_iter_index }}.json"
    flat: yes
  when:
    - inventory_hostname == groups['clients'][0]

- name: Cleanup in between tests (conditional)
  shell: rm -rf {{ hostvars[inventory_hostname]['gbench_client_mountpoint'] }}fio/*
  args:
    executable: /bin/bash
  when:
    - inventory_hostname == groups['clients'][0]
    - test_vars.cleanup_between and fio_iter_index != test_vars.iterations - 1

- name: Cleanup post last iteration of test (conditional)
  shell: rm -rf {{ hostvars[inventory_hostname]['gbench_client_mountpoint'] }}fio/*
  args:
    executable: /bin/bash
  when:
    - inventory_hostname == groups['clients'][0]
    - test_vars.cleanup_last and fio_iter_index == test_vars.iterations - 1
