---
# This task determines the number of bricks needed and configures
# the bricks on the respective server hosts

- name: Generate ssh keys
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_file: .ssh/id_rsa

- name: Copy ssh public key
  shell: cat ~/.ssh/id_rsa.pub
  register: ssh_keys

# TODO: Deply server host keys in servers only and same with client
- name: Deploy keys on all hosts
  authorized_key: user=root key="{{ item[0] }}"
  delegate_to: "{{ item[1] }}"
  with_nested:
   - "{{ ssh_keys.stdout }}"
   - "{{groups['all']}}"
