---
# This is the main playbook that runs various role based plays

# Gather and cache all facts from hosts
- name: Cache facts from all hosts
  hosts: all
  gather_facts: true
  tags:
    - always

# Run through some common tasks on all nodes
- name: Prepare all hosts
  hosts: all
  gather_facts: false
  roles:
    - common
  tags:
    - preparehosts

- name: Enable SSH trust across hosts
  hosts: all
  gather_facts: false
  roles:
    - passwdless-ssh-mesh
  tags:
    - preparehosts

# Run through some common tasks on all nodes
- name: Install Gluster repositories
  hosts: all
  gather_facts: false
  roles:
    - install-repos
  tags:
    - glinstall

# Run gluster sources installation on the servers
- name: Prepare Gluster servers
  hosts: servers
  gather_facts: false
  roles:
    - prepare-gluster-server
  tags:
    - glinstall

# Run gluster sources installation on the clients
- name: Prepare Gluster clients
  hosts: clients
  gather_facts: false
  roles:
    - prepare-gluster-client
  tags:
    - glinstall

# Check passed in configuration requests and validate against the setup
# Also, generate required variable files for use in subsequent plays
- name: Check setup and prepare storage and volume configuration
  hosts: localhost
  gather_facts: false
  roles:
    - validate-setup
  tags:
    - createvolume

- name: Cleanup gluster mounts
  hosts: clients
  gather_facts: false
  roles:
    - cleanup-gluster-clients
  tags:
    - createvolume

- name: Cleanup Gluster volume
  hosts: servers
  gather_facts: false
  roles:
    - cleanup-gluster-volume
  tags:
    - createvolume

# Prepare bricks on servers, based on the configuration generated
- name: Prepare brick mounts
  hosts: servers
  gather_facts: false
  roles:
    - prepare-brick-mounts
  tags:
    - createvolume

- name: Prepare Gluster volume
  hosts: servers
  gather_facts: false
  roles:
    - create-gluster-volume
  tags:
    - createvolume

- name: Mount Gluster volume
  hosts: clients
  gather_facts: false
  roles:
    - mount-gluster-volume
  tags:
    - createvolume

- name: Run benchmark tests
  hosts: all
  gather_facts: false
  roles:
    - run-bench-tests
  tags:
    - runtests

