---
# This task list install Gluster server bits on CentOS (and clones)
# Starts the gluster service on the hosts

- name: Include repository variables passed in
  include_vars:
    file: "{{ repo_details }}"
  tags:
    - packagesall
    - packagesserver

# Install Gluster server
# TODO: the manner to get el7 should be nicer,
- name: Install gluster server bits
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - glusterfs
    - glusterfs-devel
    - glusterfs-debuginfo
    - glusterfs-server
    - glusterfs-client-xlators
    - glusterfs-extra-xlators
    - glusterfs-fuse
    - glusterfs-api-devel
    - glusterfs-resource-agents
    - glusterfs-rdma
    - glusterfs-geo-replication
    - glusterfs-events
  tags:
    - packagesall
    - packagesserver

- name: Enable glusterd service on hosts
  systemd:
    state: started
    enabled: yes
    name: glusterd
  tags:
    - glusterinit
