---
# This task list install dependency, Gluster server bits on CentOS (and clones)
# Starts the gluster service on the hosts

# Install lvm
- name: Install lvm bits
  yum:
    name: lvm2
    state: present

- name: Include repository variables passed in
  include_vars:
    file: "{{ repo_details }}"

# Install Gluster server
# TODO: the manner to get el7 should be nicer,
- name: Install gluster server bits
  yum:
    name: "glusterfs-server-{{ gluster_major_release }}.{{ gluster_minor_release }}.el{{ ansible_distribution_major_version }}"
    state: present
  when:
    - repository_type|lower == "upstream" or repository_type|lower == "upstream-qa" or repository_type|lower == "specific"

- name: Install gluster server specific/nightly/downstream bits
  yum:
    name: "glusterfs-server"
    state: present
  when:
    - repository_type|lower == "nightly" or repository_type|lower == "downstream"

- name: Enable glusterd service on hosts
  systemd:
    state: started
    enabled: yes
    name: glusterd
